sudo: required

services:
  - docker

script:
 - docker pull ubuntu:bionic
 - docker run -v $PWD:/mnt ubuntu:bionic /bin/bash -x -c "/mnt/build.sh"

after_success:
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath
  - wget https://raw.githubusercontent.com/nomad-desktop/nxos-repository-util/master/nxos-repository-util.sh -O nxos-repository-util.sh
  - chmod +x nxos-repository-util.sh
  - ./nxos-repository-util.sh upload development $PWD/AppImageKit/build/libappimage*.deb

after_failure:
  - echo "Failure"

branches:
  except:
    - master

notifications:
  email: false
