sudo: required
dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://archive.neon.kde.org/dev/stable/ bionic main'
      key_url: 'http://archive.neon.kde.org/public.key'

branches:
  except:
    - master

notifications:
  email: false